version: "3.8"
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # management UI
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders

  adminer:
    image: adminer:latest
    container_name: adminer
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: orders
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - 8080:8080

  orderbook-migrations:
    container_name: orderbook-migrations
    build:
      dockerfile: Dockerfile
      context: ./orderbook-migrations
    volumes:
      - ./orderbook-migrations/migrations:/migrations
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432
    depends_on:
      - postgres



